# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ZGU5NzY3NTI1YWY1ZTA0MGQzY2M1MjU1YTE2NTY5M2NlMjczOWVkZjY5NTM1YjJiNjEzMzUzYmJlZjYzMmU5YWM3MDM1MGZmMzI5ODkwOGQwN2VmNmZlNzIwNzI4ZTE4ODk3MmU4OWU5ZjAwZmJmYTkzNWU4YjY2ZTU4ZWZlZDI=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
